name: placeholder_utils
description: A plugin to provide useful tools for developers in the development process.

version: 0.0.1
homepage: https://www.alpr.dev
repository: https://github.com/repfly/placeholder_utils

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0




