# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:

  push:
    branches: [master,develop]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [develop,master]




jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter test
    
