# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      FLUTTER_VERSION: "2.5.3"
      
      
    steps:
      - uses: actions/checkout@v3
        with:
          flutter-version: $
          
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
